version: "3.8"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/caddyfile/:/etc/caddy/
      - ${SRC}:/srv
      - ./caddy/caddy-data:/data
      - ./caddy/caddy-config:/config
    restart: unless-stopped